name: Upload Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build All
        shell: cmd
        run: build_all.bat

      - name: Pack Release
        uses: ThirteenAG/zip-release@master
        with:
          path: ./*
          type: 'zip'
          filename: 'SA.CommunityMapFixes.7z'
          exclusions: 'data extras models *.bat *7z *.md *.img'

      - name: Pack Extras
        uses: ThirteenAG/zip-release@master
        with:
         path: extras/modloader/*
         type: 'zip'
         filename: 'SA.CommunityMapExtras.7z'
         exclusions: 'modloader data models scripts *.bat *7z *.md *.img'

      - name: Get Release Info
        id: release_info
        uses: cardinalby/git-get-release-action@1.2.2
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: latest

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: ${{ steps.release_info.outputs.name }}
          body: ${{ steps.release_info.outputs.body }}
          tag: ${{ steps.release_info.outputs.tag_name }}
          artifacts: SA.CommunityMapFixes.7z,SA.CommunityMapExtras.7z
